      *-----------------------------------------------------------------
      * CBLC72A - quote in column 72 (P-084)
      * Q: A quote in column 72 looks like it closes the literal, and
      *    the continuation line starts with two quotes (CCVS85 NC215A).
      *    Is the column-72 quote the first of a doubled quote?
      * If so W-A ends with '"YZ'. If it closes, compilation fails.
      * The column positions ARE the observation. Do not re-indent or
      * trim this file; it is generated by tools/zos-probe/gen-col72.sh.
      * Scenario notes (Japanese): docs/zos-probe/scenarios.md
      *-----------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. CBLC72A.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       COPY PRBWS.
       01  W-A PIC X(80) VALUE "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      -    ""YZ".
       PROCEDURE DIVISION.
       MAIN-PARA.
           MOVE "C.P084.A" TO PRB-CASE
           MOVE W-A TO PRB-IN MOVE 80 TO PRB-LEN
           MOVE W-A(41:40) TO PRB-TEXT
           PERFORM PRB-EMIT
           GOBACK.
       COPY PRBPD.
