      *-----------------------------------------------------------------
      * CBLC72C - quote in column 72 (P-084)
      * Baseline: an ordinary continuation of a literal that is still
      * open in column 72. Both implementations should agree.
      * The column positions ARE the observation. Do not re-indent or
      * trim this file; it is generated by tools/zos-probe/gen-col72.sh.
      * Scenario notes (Japanese): docs/zos-probe/scenarios.md
      *-----------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. CBLC72C.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       COPY PRBWS.
       01  W-C PIC X(80) VALUE "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      -    "DEF".
       PROCEDURE DIVISION.
       MAIN-PARA.
           MOVE "C.P084.C" TO PRB-CASE
           MOVE W-C TO PRB-IN MOVE 80 TO PRB-LEN
           MOVE W-C(41:40) TO PRB-TEXT
           PERFORM PRB-EMIT
           GOBACK.
       COPY PRBPD.
