      *-----------------------------------------------------------------
      * CBLC72B - quote in column 72 (P-084)
      * Q: A literal closes in column 72 and the continuation line
      *    starts another literal with a quote. Two literals (closed),
      *    or one literal (doubled quote)?
      * If closed, W-B is 'AAA...ABBB'.
      * The column positions ARE the observation. Do not re-indent or
      * trim this file; it is generated by tools/zos-probe/gen-col72.sh.
      * Scenario notes (Japanese): docs/zos-probe/scenarios.md
      *-----------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. CBLC72B.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       COPY PRBWS.
       01  W-B                 PIC X(80).
       PROCEDURE DIVISION.
       MAIN-PARA.
           MOVE SPACES TO W-B
           STRING "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      -    "BBB" DELIMITED BY SIZE INTO W-B
           END-STRING
           MOVE "C.P084.B" TO PRB-CASE
           MOVE W-B TO PRB-IN MOVE 80 TO PRB-LEN
           MOVE W-B(41:40) TO PRB-TEXT
           PERFORM PRB-EMIT
           GOBACK.
       COPY PRBPD.
