CREATE TABLE COBOL_CONVERSATION (
    CONVERSATION_ID VARCHAR(128) NOT NULL,
    CONVERSATION_VERSION BIGINT NOT NULL,
    OWNER_NAME VARCHAR(256) NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    LEASE_TOKEN VARCHAR(128),
    LEASED_UNTIL BIGINT NOT NULL,
    ENVELOPE BLOB NOT NULL,
    CONSTRAINT COBOL_CONVERSATION_PK PRIMARY KEY (CONVERSATION_ID)
);

CREATE INDEX COBOL_CONVERSATION_IX1 ON COBOL_CONVERSATION (EXPIRES_AT);

CREATE TABLE COBOL_TASK_OUTCOME (
    OWNER_NAME VARCHAR(256) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
    FINGERPRINT CHAR(64) NOT NULL,
    RETAIN_UNTIL BIGINT NOT NULL,
    REPLY BLOB,
    CONSTRAINT COBOL_TASK_OUTCOME_PK PRIMARY KEY (OWNER_NAME, IDEMPOTENCY_KEY)
);

CREATE INDEX COBOL_TASK_OUTCOME_IX1 ON COBOL_TASK_OUTCOME (RETAIN_UNTIL);

CREATE TABLE COBOL_TERMINAL (
    TERMINAL_ID VARCHAR(4) NOT NULL,
    OWNER_NAME VARCHAR(256) NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    LEASE_TOKEN VARCHAR(128),
    LEASED_UNTIL BIGINT NOT NULL,
    CONVERSATION_ID VARCHAR(128),
    CONVERSATION_VERSION BIGINT,
    NEXT_TRANSID VARCHAR(4),
    SCREEN_VERSION BIGINT NOT NULL,
    SCREEN BLOB,
    CONSTRAINT COBOL_TERMINAL_PK PRIMARY KEY (TERMINAL_ID)
);

CREATE INDEX COBOL_TERMINAL_IX1 ON COBOL_TERMINAL (EXPIRES_AT);

CREATE TABLE COBOL_START (
    REQUEST_ID VARCHAR(8) NOT NULL,
    START_TOKEN VARCHAR(128) NOT NULL,
    TRANSID VARCHAR(4) NOT NULL,
    TERMINAL_ID VARCHAR(4),
    EXPIRES_AT BIGINT NOT NULL,
    START_DATA BLOB,
    RTRANSID VARCHAR(8),
    RTERMID VARCHAR(8),
    QUEUE_NAME VARCHAR(8),
    OWNER_NAME VARCHAR(256) NOT NULL,
    USER_ID VARCHAR(8),
    CHANNEL_NAME VARCHAR(16),
    CHANNEL_DATA BLOB,
    CONSTRAINT COBOL_START_PK PRIMARY KEY (REQUEST_ID)
);

CREATE INDEX COBOL_START_IX1 ON COBOL_START (EXPIRES_AT);

CREATE TABLE COBOL_TD_QUEUE (
    QUEUE_NAME VARCHAR(4) NOT NULL,
    NEXT_SEQUENCE BIGINT NOT NULL,
    RECORD_COUNT BIGINT NOT NULL,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TASK_TOKEN VARCHAR(128),
    TASK_UNTIL BIGINT NOT NULL,
    CONSTRAINT COBOL_TD_QUEUE_PK PRIMARY KEY (QUEUE_NAME)
);

CREATE TABLE COBOL_TD_RECORD (
    QUEUE_NAME VARCHAR(4) NOT NULL,
    SEQUENCE_NO BIGINT NOT NULL,
    RECORD_DATA BLOB NOT NULL,
    CONSTRAINT COBOL_TD_RECORD_PK PRIMARY KEY (QUEUE_NAME, SEQUENCE_NO)
);
