CREATE TABLE COBOL_CONVERSATION (
    CONVERSATION_ID VARCHAR(128) NOT NULL,
    CONVERSATION_VERSION BIGINT NOT NULL,
    OWNER_NAME VARCHAR(256) NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    LEASE_TOKEN VARCHAR(128),
    LEASED_UNTIL BIGINT NOT NULL,
    ENVELOPE BLOB NOT NULL,
    CONSTRAINT COBOL_CONVERSATION_PK PRIMARY KEY (CONVERSATION_ID)
);

CREATE INDEX COBOL_CONVERSATION_IX1 ON COBOL_CONVERSATION (EXPIRES_AT);

CREATE TABLE COBOL_TASK_OUTCOME (
    OWNER_NAME VARCHAR(256) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
    FINGERPRINT CHAR(64) NOT NULL,
    RETAIN_UNTIL BIGINT NOT NULL,
    REPLY BLOB,
    CONSTRAINT COBOL_TASK_OUTCOME_PK PRIMARY KEY (OWNER_NAME, IDEMPOTENCY_KEY)
);

CREATE INDEX COBOL_TASK_OUTCOME_IX1 ON COBOL_TASK_OUTCOME (RETAIN_UNTIL);
