#!/bin/sh
# CBLC72A / B / C を作る (P-084)。
# 観測の対象は「引用符が 72 桁目にあること」そのものなので、手で書かずに
# 桁を数えて作る。できた原文を編集器で整えると観測が壊れる。
# 使い方: sh tools/zos-probe/gen-col72.sh
cd "$(dirname "$0")/cobol" || exit 2

# $1 を $2 の字で 71 桁まで埋め、72 桁目に引用符を置く
closed_at_72() {
  s=$1
  while [ ${#s} -lt 71 ]; do s="$s$2"; done
  printf '%s"\n' "$s"
}

# 72 桁目まで閉じない (72 桁目も定数の中身)
open_to_72() {
  s=$1
  while [ ${#s} -lt 72 ]; do s="$s$2"; done
  printf '%s\n' "$s"
}

header() {
  cat <<EOF
      *-----------------------------------------------------------------
      * $1 - quote in column 72 (P-084)
EOF
  printf '%s\n' "$2" | sed 's/^/      * /'
  cat <<EOF
      * The column positions ARE the observation. Do not re-indent or
      * trim this file; it is generated by tools/zos-probe/gen-col72.sh.
      * Scenario notes (Japanese): docs/zos-probe/scenarios.md
      *-----------------------------------------------------------------
       IDENTIFICATION DIVISION.
       PROGRAM-ID. $1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       COPY PRBWS.
EOF
}

trailer() {
  cat <<EOF
           MOVE "C.P084.$1" TO PRB-CASE
           MOVE $2 TO PRB-IN MOVE 80 TO PRB-LEN
           MOVE $2(41:40) TO PRB-TEXT
           PERFORM PRB-EMIT
           GOBACK.
       COPY PRBPD.
EOF
}

{
  header CBLC72A "Q: A quote in column 72 looks like it closes the literal, and
   the continuation line starts with two quotes (CCVS85 NC215A).
   Is the column-72 quote the first of a doubled quote?
If so W-A ends with '\"YZ'. If it closes, compilation fails."
  closed_at_72 '       01  W-A PIC X(80) VALUE "' A
  echo '      -    ""YZ".'
  echo '       PROCEDURE DIVISION.'
  echo '       MAIN-PARA.'
  trailer A W-A
} > CBLC72A.cbl

{
  header CBLC72B "Q: A literal closes in column 72 and the continuation line
   starts another literal with a quote. Two literals (closed),
   or one literal (doubled quote)?
If closed, W-B is 'AAA...ABBB'."
  echo '       01  W-B                 PIC X(80).'
  echo '       PROCEDURE DIVISION.'
  echo '       MAIN-PARA.'
  echo '           MOVE SPACES TO W-B'
  closed_at_72 '           STRING "' A
  echo '      -    "BBB" DELIMITED BY SIZE INTO W-B'
  echo '           END-STRING'
  trailer B W-B
} > CBLC72B.cbl

{
  header CBLC72C "Baseline: an ordinary continuation of a literal that is still
open in column 72. Both implementations should agree."
  open_to_72 '       01  W-C PIC X(80) VALUE "' C
  echo '      -    "DEF".'
  echo '       PROCEDURE DIVISION.'
  echo '       MAIN-PARA.'
  trailer C W-C
} > CBLC72C.cbl
